const initialItems = [
  {
    name: 'Star Wars',
    year: 1977,
    price: 100,
    image: '/imgs/star_wars_e4.jpg',
    format: 'VHS',
    description:
      'This is it. The original theatrical version, before all the crazy stuff George Lucas did. Hans shot first.',
    id: 'laksd78',
    sellerId: 'qoi2376d',
    seller: 'Ringo Skywalker',
  },
  {
    name: 'Frozen',
    year: 2013,
    price: 0,
    image: '/imgs/frozen_dvd.jpg',
    format: 'DVD',
    description:
      'Free, zero, zilch, nada. Just take it. Please, just take it. If I have to listen to "Let it go" one more time I\'ll lose it.',
    id: 'alkausd8',
    sellerId: 'o8iyash',
    seller: 'Disney Mom',
  },
  {
    name: 'Old Boy',
    year: 2003,
    price: 15,
    image: '/imgs/oldboy_bd.jpg',
    format: 'Blu Ray',
    description:
      'The original Korean version in the best resolution available.',
    id: 'lasd9h3',
    sellerId: 'osdi7sd',
    seller: 'Parker Shenlok',
  },
  {
    name: 'Star Wars - The Phantom Menace',
    year: 1999,
    price: 5,
    image: '/imgs/star_wars_e1.jpg',
    format: 'DVD',
    description:
      "I waited 20 years for this movie. Now I can't wait to get rid of it.",
    id: 'laksd79',
    sellerId: 'qoi2376d',
    seller: 'Ringo Skywalker',
  },
  {
    name: 'Predestination',
    year: 2014,
    price: 15,
    image: '/imgs/predestination_dvd.jpg',
    format: 'DVD',
    description:
      "I had to watch this one four times, but I finally understood. Not the crazyest time paradox I've ever seen.",
    id: 'lkj34hg',
    sellerId: 'o8ikesh',
    seller: 'The Doctor',
  },
  {
    name: 'Beauty and the Beast',
    year: 1991,
    price: 5,
    image: '/imgs/beauty-beast-vhs.jpg',
    format: 'VHS',
    description:
      "I actually like this movie! But since it's on Netflix, I have no need for this old VHS tape. Price negotiable.",
    id: 'alkausd9',
    sellerId: 'o8iyash',
    seller: 'Disney Mom',
  },
  {
    name: 'Back to the Future Trilogy',
    year: 1985,
    price: 30,
    image: '/imgs/bbtf_vhs.jpg',
    format: 'VHS',
    description:
      'Before making-ofs and extras were a thing, this box set had a fourth tape just for that! Really vintage, in good condition.',
    id: 'alk83sd9',
    sellerId: 'o8ikesh',
    seller: 'The Doctor',
  },
  {
    name: 'The Last Dragon',
    year: 1985,
    price: 5,
    image: '/imgs/last_dragon_dvd.jpg',
    format: 'DVD',
    description:
      "I loved this movie when I was a kid. Watched whenever it was on TV. I thought the DVD would bring me joy! Well, let's say the movie hasn't aged well...",
    id: 'alk4k3sd9',
    sellerId: 'o8ik6sh',
    seller: 'Bruce Leroy',
  },
  {
    name: 'Donnie Darko',
    year: 2001,
    price: 20,
    image: '/imgs/donnie_darko_vhs.jpg',
    format: 'VHS',
    description:
      "A modern classic time-travelling movie. The logic's sound here, too.",
    id: 'alk83fd9',
    sellerId: 'o8ikesh',
    seller: 'The Doctor',
  },
  {
    name: 'Crouching Tiger, Hidden Dragon',
    year: 2001,
    price: 30,
    image: '/imgs/CTHD_BD.jpg',
    format: 'Blu Ray',
    description:
      "A real masterpiece that deserves to be seen in FullHD. I'm selling this to buy in 4K.",
    id: 'alk4k2g29',
    sellerId: 'o8ik6sh',
    seller: 'Bruce Leroy',
  },
  {
    name: 'Safety Not Guaranteed',
    year: 2012,
    price: 15,
    image: '/imgs/safety_not_guaranteed_BD.jpg',
    format: 'Blu Ray',
    description:
      "Could as well be a documentary. You'd be amazed at how many apparently crazyheads actually got to time-travel.",
    id: 'lrk83fd9',
    sellerId: 'o8ikesh',
    seller: 'The Doctor',
  },
  {
    name: 'Pinocchio',
    year: 1940,
    price: 10,
    image: '/imgs/pinocchio_dvd.jpg',
    format: 'DVD',
    description:
      'I loved this movie as a kid! My kids got scared of the donkey scene, though. I guess time changes.',
    id: 'alkk2lsd9',
    sellerId: 'o8iyash',
    seller: 'Disney Mom',
  },
  {
    name: 'About Time',
    year: 2013,
    price: 10,
    image: '/imgs/about_time_BD.jpg',
    format: 'Blu Ray',
    description:
      "I've met a guy just like the main character on this one. Way nastier objectives, though.",
    id: 'ak4k3fd9',
    sellerId: 'o8ikesh',
    seller: 'The Doctor',
  },
  {
    name: 'Ewoks Double Feature: Caravan of Courage and The Battle for Endor',
    year: 1984,
    price: 15,
    image: '/imgs/Star_Wars_Ewoks_2F_DVD.jpg',
    format: 'DVD',
    description:
      'Other than the Holiday Special, those are the most forgettable entries in the Star Wars universe. But kids love it.',
    id: 'ak434fd29',
    sellerId: 'qoi2376d',
    seller: 'Ringo Skywalker',
  },
  {
    name: 'Enter The Dragon',
    year: 1973,
    price: 20,
    image: '/imgs/enter_the_dragon_DVD.jpg',
    format: 'DVD',
    description: "Bruce Lee's last movie, and one of his best work.",
    id: 'alk4k2gd9',
    sellerId: 'o8ik6sh',
    seller: 'Bruce Leroy',
  },
  {
    name: 'Somewhere In Time',
    year: 1980,
    price: 10,
    image: '/imgs/somewhere_in_time_VHS.jpg',
    format: 'VHS',
    description:
      'Nice movie, crazy theory. But if you ever find someone who can actually do that, let me know.',
    id: 'ak4k3fd30',
    sellerId: 'o8ikesh',
    seller: 'The Doctor',
  },
  {
    name: 'Yip Man Trilogy',
    year: 2008,
    price: 35,
    image: '/imgs/yip_man_BD.jpg',
    format: 'Blu Ray',
    description:
      "I don't know if the part of the character being Bruce Lee's original master is true, but the movies are rad!",
    id: 'alk4k2f29',
    sellerId: 'o8ik6sh',
    seller: 'Bruce Leroy',
  },
  {
    name: "Bill and Ted's Excellent Adventure",
    year: 1989,
    price: 10,
    image: '/imgs/BTEA_VHS.jpg',
    format: 'VHS',
    description:
      'Nice kids, met them once. Nice phone booth, too. Funny story: they gave me the tape themselves in 1834.',
    id: 'ak4k3fd26',
    sellerId: 'o8ikesh',
    seller: 'The Doctor',
  },
  {
    name: 'Star Wars Holiday Special',
    year: 1978,
    price: 30,
    image: '/imgs/SWHS_DVD.jpg',
    format: 'DVD',
    description:
      "The infamous Holiday Special, which most people involved would rather forget. They are right, this thing's awful. It's still a rarity, though.",
    id: 'ak434fd26',
    sellerId: 'qoi2376d',
    seller: 'Ringo Skywalker',
  },
  {
    name: 'In The Mood For Love',
    year: 2000,
    price: 10,
    image: '/imgs/Mood_for_love_DVD.jpg',
    format: 'DVD',
    description:
      "The best chinese movie you never saw. It's a real masterpiece.",
    id: 'lasd9h34',
    sellerId: 'osdi7sd',
    seller: 'Parker Shenlok',
  },
];

const initialUsers = {
  ringo: {
    id: 'qoi2376d',
    name: 'Ringo Skywalker',
    password: 'r',
  },
  elza: {
    id: 'o8iyash',
    name: 'Disney Mom',
    password: 'e',
  },
  parker: {
    id: 'osdi7sd',
    name: 'Parker Shenlok',
    password: 'p',
  },
  doctor: {
    id: 'o8ikesh',
    name: 'The Doctor',
    password: 'd',
  },
  bruce: {
    id: 'o8ik6sh',
    name: 'Bruce Leroy',
    password: 'b',
  },
};

module.exports = { initialItems, initialUsers };
